#!/usr/bin/env bash

die() { echo "Error: $*" >&2; exit 1; }

ensure_idf() {
  # idf.py already in PATH
  if command -v idf.py >/dev/null 2>&1; then
    return 0
  fi

  if [[ -n "${IDF_PATH:-}" && -f "${IDF_PATH}/export.sh" ]]; then
    # shellcheck disable=SC1090
    source "${IDF_PATH}/export.sh"
  else
    die "ESP-IDF environment not found.
Set IDF_PATH and run:
  source \$IDF_PATH/export.sh
or install ESP-IDF from Espressif."
  fi

  command -v idf.py >/dev/null 2>&1 \
    || die "ESP-IDF environment loaded, but idf.py is still missing."
}

is_project() {
  local project_dir="$1"

  [[ -f "${project_dir}/CMakeLists.txt" ]] && return 0 || return 1
}

update_sdkconfig_settings() {
  local sdkconfig_path="$1"
  shift

  [[ -f "$sdkconfig_path" ]] || die "sdkconfig not found: ${sdkconfig_path}"
  [[ $# -gt 0 ]] || die "No sdkconfig settings provided"

  python3 - "$sdkconfig_path" "$@" <<'PY' || die "Failed to update sdkconfig"
import sys

sdkconfig_path = sys.argv[1]
pairs = dict((k.strip(), v.strip()) for k, v in (arg.split("=", 1) for arg in sys.argv[2:]))

with open(sdkconfig_path, "r", encoding="utf-8") as f:
    lines = f.read().splitlines()

seen = set()
out_lines = []

for line in lines:
    replaced = False
    for key, value in pairs.items():
        line = line.strip()
        if line.startswith(f"{key}=") or \
          line.startswith(f"# {key} is not set"):
            out_lines.append(f"{key}={value}")
            seen.add(key)
            replaced = True
            break
    if not replaced:
        out_lines.append(line)

for key, value in pairs.items():
    if key not in seen:
        out_lines.append(f"{key}={value}")

with open(sdkconfig_path, "w", encoding="utf-8") as f:
    f.write("\n".join(out_lines) + "\n")
PY
}

build_project() {
  local target="$1"
  local project_dir="$2"

  [[ -n "$target" ]] || die "Missing target"

  [[ -d "$project_dir" ]] || die "Project directory does not exist: $project_dir"

  if ! is_project "$project_dir"; then
    die "Directory is not a project: $project_dir"
  fi

  ensure_idf

  echo
  echo "============================================================"
  echo "==> BUILDING PROJECT"
  echo "    Project : ${project_dir}"
  echo "    Target  : ${target}"
  echo "============================================================"
  echo

  pushd "$project_dir" >/dev/null

  idf.py -B "build_${target}" set-target "${target}" build

  popd >/dev/null
}

setup_project() {
  local target="$1"
  local project_dir="$2"
  local usb="$3"

  [[ -n "$target" ]] || die "Missing target"

  [[ -d "$project_dir" ]] || die "Project directory does not exist: $project_dir"

  if ! is_project "$project_dir"; then
    die "Directory is not a project: $project_dir"
  fi

  [[ -n "$usb" ]] || die "Missing usb"

  [[ "$usb" == "JTAG" || "$usb" == "UART" ]] || die "Invalid usb value: $usb (must be JTAG or UART)"

  ensure_idf

  local usb_port=""
  if [[ "$usb" == "JTAG" ]]; then
    usb_port="/dev/ttyACM0"
  else  # UART
    usb_port="/dev/ttyUSB0"
  fi

  echo
  echo "============================================================"
  echo "==> SETTING UP PROJECT"
  echo "    Project : ${project_dir}"
  echo "    Target  : ${target}"
  echo "    USB     : ${usb}"
  echo "============================================================"
  echo

  pushd "$project_dir" >/dev/null

  idf.py -B "build_${target}" set-target "${target}"

  local sdkconfig_defaults_path="${project_dir}/sdkconfig.defaults"
  [[ -f "$sdkconfig_defaults_path" ]] || touch "$sdkconfig_defaults_path"

  local defaults_settings=(
    "CONFIG_NEWLIB_STDIN_LINE_ENDING_CRLF=y"
    "CONFIG_ESP_SYSTEM_USE_FRAME_POINTER=y"
    "CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT=y"
    "CONFIG_LOG_DEFAULT_LEVEL_INFO=y"
  )

  update_sdkconfig_settings "$sdkconfig_defaults_path" "${defaults_settings[@]}"

  idf.py -B "build_${target}" reconfigure

  local sdkconfig_path="${project_dir}/sdkconfig"

  [[ -f "$sdkconfig_path" ]] || die "sdkconfig not found: ${sdkconfig_path}"

  local settings=(
    "CONFIG_ESPTOOLPY_HEADER_FLASHSIZE_UPDATE=y"
  )
  if [[ "$usb" == "JTAG" ]]; then
    settings+=(
	  "CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=y"
    )
  else  # UART
    settings+=(
      "CONFIG_ESP_CONSOLE_UART_DEFAULT=y"
    )
  fi

  update_sdkconfig_settings "$sdkconfig_path" "${settings[@]}"

  idf.py -B "build_${target}" reconfigure

  mkdir -p ".vscode"

  cat > ".vscode/settings.json" <<EOF
  {
      "idf.openOcdConfigs": [
          "board/${target}-builtin.cfg"
      ],
      "idf.customExtraVars": {
          "IDF_TARGET": "${target}"
      },
      "idf.buildPath": "\${workspaceFolder}/build_${target}",
      "idf.flashType": "UART",
      "idf.port": "${usb_port}",
      "idf.openOcdLaunchArgs": [
          "-d\${config:idf.openOcdDebugLevel}",
          "\${config:idf.openOcdConfigs,-f}",
          "-c",
          "init",
          "-c",
          "reset halt"
      ]
  }
EOF

  cat > ".vscode/launch.json" <<EOF
  {
      "configurations": [
          {
              "type": "gdbtarget",
              "request": "attach",
              "name": "debug",
              "program": "\${workspaceFolder}/build_${target}/\${command:espIdf.getProjectName}.elf",
              "initCommands": [
                  "mon reset halt",
                  "maintenance flush register-cache"
              ],
              "gdb": "\${command:espIdf.getToolchainGdb}",
              "target": {
                  "connectCommands": [
                      "set remotetimeout 20",
                      "-target-select extended-remote localhost:3333"
                  ]
              }
          }
      ]
  }
EOF

  popd >/dev/null
}
